// Code generated by hertz generator.

package app

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	model "github.com/fahmiauliarahman/poc-doku-qris/biz/model/app"
)

// GenerateQris .
// @router v1/qris/generate [POST]
func GenerateQris(ctx context.Context, c *app.RequestContext) {
	resp := new(model.GenerateQrisResponse)

	c.JSON(consts.StatusNotFound, nil)

	c.JSON(consts.StatusOK, resp)
}

// QueryQris .
// @router v1/qris/query [POST]
func QueryQris(ctx context.Context, c *app.RequestContext) {
	resp := new(model.QueryQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// RefundQris .
// @router v1/qris/refund [POST]
func RefundQris(ctx context.Context, c *app.RequestContext) {
	resp := new(model.RefundQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// DecodeQris .
// @router v1/qris/decode [POST]
func DecodeQris(ctx context.Context, c *app.RequestContext) {
	resp := new(model.DecodeQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// PaymentQris .
// @router v1/qris/payment [POST]
func PaymentQris(ctx context.Context, c *app.RequestContext) {
	resp := new(model.PaymentQrisResponse)

	c.JSON(consts.StatusOK, resp)
}
