// Code generated by hertz generator.

package main

import (
	"context"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithExitWaitTime(3 * time.Second))

	// add graceful shutdown
	h.OnShutdown = append(h.OnShutdown, func(ctx context.Context) {
		<-ctx.Done()
	})

	register(h)
	h.Spin()
}
