// Code generated by hertz generator.

package app

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	types "github.com/fahmiauliarahman/poc-doku-qris/internal/types/app"
)

// GenerateQris .
// @router v1/qris/generate [POST]
func GenerateQris(ctx context.Context, c *app.RequestContext) {

	resp := new(types.GenerateQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryQris .
// @router v1/qris/query [POST]
func QueryQris(ctx context.Context, c *app.RequestContext) {

	resp := new(types.QueryQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// RefundQris .
// @router v1/qris/refund [POST]
func RefundQris(ctx context.Context, c *app.RequestContext) {

	resp := new(types.RefundQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// DecodeQris .
// @router v1/qris/decode [POST]
func DecodeQris(ctx context.Context, c *app.RequestContext) {

	resp := new(types.DecodeQrisResponse)

	c.JSON(consts.StatusOK, resp)
}

// PaymentQris .
// @router v1/qris/payment [POST]
func PaymentQris(ctx context.Context, c *app.RequestContext) {

	resp := new(types.PaymentQrisResponse)

	c.JSON(consts.StatusOK, resp)
}
