// Code generated by hertz generator.

package app

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _qrisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _decodeqrisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _generateqrisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paymentqrisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryqrisMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refundqrisMw() []app.HandlerFunc {
	// your code...
	return nil
}
